Added SHA256 in real time
Heavy-Vehicle-Networking-At-U-Tulsa/CAN-Logger-3 pull request #6
Opened 2019-12-14 00:56 UTC by duyvan1995

The SHA256 firmware is in CAN_Logger_with_Autobaid_and_Requests_no_CAN2_AES_CBC

2019-12-17 20:36 UTC, jeremy-daily commented
Here are some test vectors:
```
HashSHA256Test sha256_test[] =
{
  {(unsigned char*)"",{0xe3b0c442,0x98fc1c14,0x9afbf4c8,0x996fb924,0x27ae41e4,0x649b934c,0xa495991b,0x7852b855}},
  {(unsigned char*)"abc",{0xba7816bf,0x8f01cfea,0x414140de,0x5dae2223,0xb00361a3,0x96177a9c,0xb410ff61,0xf20015ad}},
  {(unsigned char*)"abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq",{0x248d6a61,0xd20638b8,0xe5c02693,0x0c3e6039,0xa33ce459,0x64ff2167,0xf6ecedd4,0x19db06c1}},
  {(unsigned char*)"abcdefghbcdefghicdefghijdefghijkefghijklfghijklmghijklmnhijklmnoijklmnopjklmnopqklmnopqrlmnopqrsmnopqrstnopqrstu",{0xcf5b16a7,0x78af8380,0x036ce59e,0x7b049237,0x0b249b11,0xe8f07a51,0xafac4503,0x7afee9d1}},
  {(unsigned char*)"This is exactly 64 bytes long, not counting the terminating byte",{0xab64eff7,0xe88e2e46,0x165e29f2,0xbce41826,0xbd4c7b35,0x52f6b382,0xa9e7d3af,0x47c245f8}},
  {(unsigned char*)"For this sample, this 63-byte string will be used as input data",{0xf08a78cb,0xbaee082b,0x052ae070,0x8f32fa1e,0x50c5c421,0xaa772ba5,0xdbb406a2,0xea6be342}},
  {(unsigned char*)"And this textual data, astonishing as it may appear, is exactly 128 bytes in length, as are both SHA-384 and SHA-512 block sizes",{0x0ab80334,0x4830f920,0x89494fb6,0x35ad00d7,0x6164ad6e,0x57012b23,0x7722df0d,0x7ad26896}},
  {(unsigned char*)"By hashing data that is one byte less than a multiple of a hash block length (like this 127-byte string), bugs may be revealed.",{0xe4326d04,0x59653d7d,0x3514674d,0x713e74dc,0x3df11ed4,0xd30b4013,0xfd327fdb,0x9e394c26}},
  {(unsigned char*)"The quick brown fox jumps over the lazy dog",{0xd7a8fbb3,0x07d78094,0x69ca9abc,0xb0082e4f,0x8d5651e4,0x6d3cdb76,0x2d02d0bf,0x37c9e592}},
  {(unsigned char*)"This test tries to use the n-block utility from the hash library and as a matter of fact we're trying to get only 128 characters",{0x2ce675bd,0x3b70e104,0xd696d1b2,0x5bf3d42b,0x2b45cd77,0x6d4f590f,0x210f12c4,0x4bf473d5}},
};
```

2019-12-18 14:40 UTC, BenGardiner requested changes
Also:
* don't commit generates/compiled files such as `AN_Logger_with_Autobaud_and_Requests_no_CAN2_AES_CBC_SHA256/lib_mmcau.a` and `CAN_Logger_with_Autobaud_and_Requests_no_CAN2_AES_CBC_SHA256/mmcau_aes_functions.S` . I suggest adding `*.a` and `*.S` to the `.gitignore` file.

2019-12-18 14:40 UTC, BenGardiner commented on CAN_Logger_with_Autobaud_and_Requests_no_CAN2_AES_CBC_SHA256/CAN_Logger_with_Autobaud_and_Requests_no_CAN2_AES_CBC_SHA256.ino
> +unsigned char cipher_text[512];
here (see below)

2019-12-18 14:40 UTC, BenGardiner commented on CAN_Logger_with_Autobaud_and_Requests_no_CAN2_AES_CBC_SHA256/CAN_Logger_with_Autobaud_and_Requests_no_CAN2_AES_CBC_SHA256.ino
> +  for (uint32_t j=0; j < 512; j+=16){
this `512` is a magic number for the maximum size that an plaintext can be in your logging scheme. You should at least refactor this as a well-named constant. Ideally derive the value 512 (i.e. it is the buffer size, which is itself chosen b/c ...) and also comment the rationale for it.

2019-12-18 14:40 UTC, BenGardiner commented on CAN_Logger_with_Autobaud_and_Requests_no_CAN2_AES_CBC_SHA256/CAN_Logger_with_Autobaud_and_Requests_no_CAN2_AES_CBC_SHA256.ino
> +#define REPS 50
Some comment rationale is needed here. This isn't just "random RNG". Consider answering the questions: why `REPS` of `50`? why not any other value? has this been tested? Is this the same approach used somewhere else in a trusted source (e.g. boringSSL, bearSSL, NaCL, some paper...)

2019-12-18 14:40 UTC, BenGardiner commented on CAN_Logger_with_Autobaud_and_Requests_no_CAN2_AES_CBC_SHA256/CAN_Logger_with_Autobaud_and_Requests_no_CAN2_AES_CBC_SHA256.ino
> +#define RNG_CR_GO_MASK                           0x1u
This series of defines comes from somewhere else (the same strings show up in Teensy projects on the internet). You should mention where they come from I think.

2019-12-18 14:40 UTC, BenGardiner commented on CAN_Logger_with_Autobaud_and_Requests_no_CAN2_AES_CBC_SHA256/CAN_Logger_with_Autobaud_and_Requests_no_CAN2_AES_CBC_SHA256.ino
> +    RNG_CR |= RNG_CR_HA_MASK;  // high assurance, not needed
why is high assurance not needed?

2019-12-18 14:40 UTC, BenGardiner commented on CAN_Logger_with_Autobaud_and_Requests_no_CAN2_AES_CBC_SHA256/CAN_Logger_with_Autobaud_and_Requests_no_CAN2_AES_CBC_SHA256.ino
> +    data_buffer[493] = 0;
looks like you are committing test/debug changes to zero the rx error count here

2019-12-18 14:40 UTC, BenGardiner commented on CAN_Logger_with_Autobaud_and_Requests_no_CAN2_AES_CBC_SHA256/CAN_Logger_with_Autobaud_and_Requests_no_CAN2_AES_CBC_SHA256.ino
> +    data_buffer[496] = 0;
looks like you are committing test/debug changes to zero the tx error count here

2019-12-18 14:40 UTC, BenGardiner commented on CAN_Logger_with_Autobaud_and_Requests_no_CAN2_AES_CBC_SHA256/CAN_Logger_with_Autobaud_and_Requests_no_CAN2_AES_CBC_SHA256.ino
> + // pinMode(CS_CAN, OUTPUT);
more test/debug code commits?

2019-12-18 14:40 UTC, BenGardiner commented on CAN_Logger_with_Autobaud_and_Requests_no_CAN2_AES_CBC_SHA256/CAN_Logger_with_Autobaud_and_Requests_no_CAN2_AES_CBC_SHA256.ino
> +  //pinMode(CAN_SWITCH,OUTPUT);
more test/debug code commits?

2019-12-18 14:40 UTC, BenGardiner commented on CAN_Logger_with_Autobaud_and_Requests_no_CAN2_AES_CBC_SHA256/CAN_Logger_with_Autobaud_and_Requests_no_CAN2_AES_CBC_SHA256.ino
> +  //if(Can2.begin(MCP_ANY, CAN_250KBPS, MCP_16MHZ) == CAN_OK) Serial.println("MCP2515 Initialized Successfully!");
more test/debug code commits?

2019-12-18 14:40 UTC, BenGardiner commented on CAN_Logger_with_Autobaud_and_Requests_no_CAN2_AES_CBC_SHA256/CAN_Logger_with_Autobaud_and_Requests_no_CAN2_AES_CBC_SHA256.ino
> +  //Can2.setMode(MCP_NORMAL);
more test/debug code commits?

2019-12-18 14:40 UTC, BenGardiner commented on CAN_Logger_with_Autobaud_and_Requests_no_CAN2_AES_CBC_SHA256/CAN_Logger_with_Autobaud_and_Requests_no_CAN2_AES_CBC_SHA256.ino
> +    //else if (current_channel == 2) ErrorCount2++;
more test/debug code commits?

2019-12-18 14:40 UTC, BenGardiner commented on CAN_Logger_with_Autobaud_and_Requests_no_CAN2_AES_CBC_SHA256/CAN_Logger_with_Autobaud_and_Requests_no_CAN2_AES_CBC_SHA256.ino
> +      //else if (current_channel == 2) send_Can2_message(txmsg);
more test/debug code commits?

2019-12-18 14:40 UTC, BenGardiner commented on CAN_Logger_with_Autobaud_and_Requests_no_CAN2_AES_CBC_SHA256/CAN_Logger_with_Autobaud_and_Requests_no_CAN2_AES_CBC_SHA256.ino
> +  /*if (Can2.readMsgBuf(&rxId, &ext_flag, &len, rxBuf) == CAN_OK){
more test/debug code commits?

2019-12-18 14:40 UTC, BenGardiner commented on CAN_Logger_with_Autobaud_and_Requests_no_CAN2_AES_CBC_SHA256/CAN_Logger_with_Autobaud_and_Requests_no_CAN2_AES_CBC_SHA256.ino
> +        //if (RXCount2 > 0) send_Can2_message(txmsg);
more test/debug code commits? (many more instances follow that I won't continue to highlight)

2019-12-18 14:40 UTC, BenGardiner commented on CAN_Logger_with_Autobaud_and_Requests_no_CAN2_AES_CBC_SHA256/CryptoAccel.h
> +#ifndef CryptoAccel_h_
where does this header come from and what is its license?

2019-12-18 14:40 UTC, BenGardiner commented on CAN_Logger_with_Autobaud_and_Requests_no_CAN2_AES_CBC_SHA256/cau_api.h
> +/*
where does this header come from and what is its license?

2019-12-19 01:42 UTC, duyvan1995 commented on CAN_Logger_with_Autobaud_and_Requests_no_CAN2_AES_CBC_SHA256/CAN_Logger_with_Autobaud_and_Requests_no_CAN2_AES_CBC_SHA256.ino
> +      //else if (current_channel == 2) send_Can2_message(txmsg);
We replaced the CAN controller for the third CAN channel CAN2 so a new library is needed to be able to use CAN2. I commented them out for now.

2019-12-19 01:44 UTC, duyvan1995 commented on CAN_Logger_with_Autobaud_and_Requests_no_CAN2_AES_CBC_SHA256/CAN_Logger_with_Autobaud_and_Requests_no_CAN2_AES_CBC_SHA256.ino
> +#define RNG_CR_GO_MASK                           0x1u
This RNG function will be replaced by the RNG from the hardware security module ATECC608A in the future

2019-12-19 01:47 UTC, duyvan1995 commented on CAN_Logger_with_Autobaud_and_Requests_no_CAN2_AES_CBC_SHA256/CAN_Logger_with_Autobaud_and_Requests_no_CAN2_AES_CBC_SHA256.ino
> +    data_buffer[493] = 0;
There is no CAN2 so I set this information to 0 for now

2019-12-19 01:47 UTC, duyvan1995 commented on CAN_Logger_with_Autobaud_and_Requests_no_CAN2_AES_CBC_SHA256/CAN_Logger_with_Autobaud_and_Requests_no_CAN2_AES_CBC_SHA256.ino
> +    data_buffer[496] = 0;
There is no CAN2 so I set this information to 0 for now

2019-12-19 01:48 UTC, duyvan1995 commented on CAN_Logger_with_Autobaud_and_Requests_no_CAN2_AES_CBC_SHA256/CAN_Logger_with_Autobaud_and_Requests_no_CAN2_AES_CBC_SHA256.ino
> +  //if(Can2.begin(MCP_ANY, CAN_250KBPS, MCP_16MHZ) == CAN_OK) Serial.println("MCP2515 Initialized Successfully!");
We replaced the CAN controller for the third CAN channel CAN2 so a new library is needed to be able to use CAN2. I commented them out for now.

2019-12-19 15:12 UTC, jeremy-daily commented
> 
> 
> Also:
> 
>     * don't commit generates/compiled files such as `AN_Logger_with_Autobaud_and_Requests_no_CAN2_AES_CBC_SHA256/lib_mmcau.a` and `CAN_Logger_with_Autobaud_and_Requests_no_CAN2_AES_CBC_SHA256/mmcau_aes_functions.S` . I suggest adding `*.a` and `*.S` to the `.gitignore` file.

@BenGardiner The assembly files are the only available source for the working with the crypto. I'll look in the license for these source files.

2019-12-20 20:50 UTC, jeremy-daily commented on CAN_Logger_with_Autobaud_and_Requests_no_CAN2_AES_CBC_SHA256/CryptoAccel.h
> +#ifndef CryptoAccel_h_
https://github.com/PaulStoffregen/CryptoAccel/blob/master/Freescale_License.txt

2019-12-20 20:52 UTC, jeremy-daily commented on CAN_Logger_with_Autobaud_and_Requests_no_CAN2_AES_CBC_SHA256/CAN_Logger_with_Autobaud_and_Requests_no_CAN2_AES_CBC_SHA256.ino
> +  for (uint32_t j=0; j < 512; j+=16){
I changed these 512 values to a define for the BUFFER_SIZE

2019-12-20 20:53 UTC, jeremy-daily commented on CAN_Logger_with_Autobaud_and_Requests_no_CAN2_AES_CBC_SHA256/CAN_Logger_with_Autobaud_and_Requests_no_CAN2_AES_CBC_SHA256.ino
> +#define REPS 50
I'm not sure on this. @duyvan1995 where did this RNG code come from?

2019-12-20 20:58 UTC, jeremy-daily commented
I have been working on a different fork for this code: 
https://github.com/SystemsCyber/CAN-Logger-3
I've addressed some of the issues @BenGardiner brought up in that fork. I suggest we finish this pull request and move over to the new fork and keep working. There are a handful of features we need to get worked out: 
1. Provisioning,
2. J1708
3. Using the ATECC for RNGs
4. Digitally signing the encrypted binary files.
5. Digtally signing the meta_data file
6. Separating the meta_data for each binary file into their own signed files.

2019-12-20 20:58 UTC, jeremy-daily approved these changes

2019-12-20 21:15 UTC, BenGardiner commented
ok. let's move over there

2019-12-22 19:01 UTC, merged